const ROUTES = {
    HOME: "/",
    LOGIN: "/login",
    ME: "/me",
    USER_REGISTER: "/user/register",
    DIETICIAN_REGISTER: "/dietician/register",
    ADMIN_REGISTER: "/admin/register",
    PASSWORD_RESET: "/reset/password",
    NEW_PASSWORD: "/reset/password/:token",
    ADMIN_USER_DETAILS: "/admin/dashboard/users/:id",
    getAdminUserDetails: (id: string) => `/admin/dashboard/users/${id}`,
    ADMIN_DASHBOARD: "/admin/dashboard",
    TWO_FACTOR: "/2fa-login",
    REDIRECT: "/redirect",
    DIETICIAN_DASHBOARD: "/dietician/dashboard",
    CLIENT_DASHBOARD: "/client/dashboard",
    CODELOGIN_REQUEST: "/codelogin/request",
    CODELOGIN: "/codelogin",
    FORCE_CHANGE_PASSWORD: "/password/change",
    CLIENT_DETAILS: "/client-details",
    CLIENT_BLOOD_REPORT: "/client/blood-report",
    DIETICIAN_BLOOD_REPORT: "/dietician/blood-report/:clientId",
    CLIENT_ALL_PYRAMIDS: "/client/pyramids",
    DIETICIAN_CLIENT_PYRAMIDS: "/dietician/pyramids/:clientId",
}

export default ROUTES;
