const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  ME: "/me",
  USER_REGISTER: "/user/register",
  DIETICIAN_REGISTER: "/dietician/register",
  ADMIN_REGISTER: "/admin/register",
  PASSWORD_RESET: "/reset/password",
  NEW_PASSWORD: "/reset/password/:token",
  ADMIN_USER_DETAILS: "/admin/dashboard/users/:id",
  getAdminUserDetails: (id: string) => `/admin/dashboard/users/${id}`,
  ADMIN_DASHBOARD: "/admin/dashboard",
  TWO_FACTOR: "/2fa-login",
  REDIRECT: "/redirect",
  DIETICIAN_DASHBOARD: "/dietician/dashboard",
  CLIENT_DASHBOARD: "/client/dashboard",
  CODELOGIN_REQUEST: "/codelogin/request",
  CODELOGIN: "/codelogin",
  FORCE_CHANGE_PASSWORD: "/password/change",
  CLIENT_DETAILS: "/client-details",
  CLIENT_BLOOD_REPORT: "/client/blood-report",
  DIETICIAN_BLOOD_REPORT: "/dietician/blood-report/:clientId",
  FOOD_PYRAMIDS: "/food-pyramids",
  CLIENT_ALL_PYRAMIDS: "/client/pyramids",
  DIETICIAN_CLIENT_PYRAMIDS: "/dietician/pyramids/:clientId",
  CLIENT_PERIODIC_SURVEY_LIST: "/client/periodic-survey-list",
  DIETICIAN_PERIODIC_SURVEY_LIST: "/dietician/periodic-survey-list/:clientId",
  getDieticianPeriodicSurveyList: (clientId: string) =>
    `/dietician/periodic-survey-list/${clientId}`,
  DIETICIAN_INSERT_BLOOD_TEST_REPORT: "/dietician/blood-report/insert/:id",
  dieticianInsertBloodTestReport: (id: string) =>
    `/dietician/blood-report/insert/${id}`,
  DIETICIAN_MEDICAL_CHARTS: "/charts/:clientId",
  CLIENT_MEDICAL_CHARTS: "/charts",
  FOOD_PYRAMID_DETAILS: "/food-pyramids/:id",
  getFoodPyramidDetails: (id: string) => `/food-pyramids/${id}`,
};

export default ROUTES;
